project:
  type: website
  output-dir: .
  render:
    - "*.qmd"
    - "!cv/*.Rmd"
    - "!cv/*.html"

website:
  title: "Victor Coelho"
  navbar:
    left:
      - text: ""
      #  href: index.qmd
      #- text: "Portfolio"
      #  href: portfolio/index.qmd
      #- text: "Publications"
      #  href: publications/index.qmd
      #- text: "CV"
      #  href: cv/resume.pdf
  search: false  # Hidden for now, can be enabled later when site grows

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
